### ISSUE TITLE
Revival

### ISSUE THREAD

**Issue by MierenManz** [crabmusket/deno_sqlite_plugin#6]
@crabmusket, do you plan on updating this module to be compatible or should I make a fork and maintain that?

**Comment by crabmusket** [comment]
Unfortunately I won't be using Deno at work for the foreseeable future, so I don't think I'll have the time to update this. I'd encourage forking, or simply starting over taking this code as inspiration!

**Comment by MierenManz** [comment]
DjDeveloperr has started a new repo for a ffi based Sqlite3 library. So I guess this can be closed

**Comment by crabmusket** [comment]
Nice, I'll add that to the readme https://github.com/denodrivers/sqlite3
